-- USERS
CREATE TABLE USERS (
  USER_ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;

INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '나은');
INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '민준');
INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '현민');

-- MEETINGS
CREATE TABLE MEETINGS (
  MEETING_ID NUMBER PRIMARY KEY,
  MEETING_DATE DATE NOT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  CONTENT CLOB NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_MEETINGS START WITH 1 INCREMENT BY 1;

-- MEETING_ATTENDEES (N:M)
CREATE TABLE MEETING_ATTENDEES (
  MEETING_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  CONSTRAINT PK_MEETING_ATTENDEES PRIMARY KEY (MEETING_ID, USER_ID),
  CONSTRAINT FK_MA_MEETING FOREIGN KEY (MEETING_ID) REFERENCES MEETINGS(MEETING_ID) ON DELETE CASCADE,
  CONSTRAINT FK_MA_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- TASKS
CREATE TABLE TASKS (
  TASK_ID NUMBER PRIMARY KEY,
  MEETING_ID NUMBER NOT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  ASSIGNEE_ID NUMBER NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'TODO' NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE,
  CONSTRAINT FK_TASK_MEETING FOREIGN KEY (MEETING_ID) REFERENCES MEETINGS(MEETING_ID) ON DELETE CASCADE,
  CONSTRAINT FK_TASK_USER FOREIGN KEY (ASSIGNEE_ID) REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE SEQ_TASKS START WITH 1 INCREMENT BY 1;

ALTER TABLE TASKS ADD CONSTRAINT CK_TASK_STATUS
CHECK (STATUS IN ('TODO', 'IN_PROGRESS', 'DONE'));

COMMIT;

INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '종훈');
INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '서연');
INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '지훈');
INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '하은');
INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '도윤');
INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '수아');
INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '예준');
INSERT INTO USERS (USER_ID, NAME) VALUES (SEQ_USERS.NEXTVAL, '지우');

COMMIT;